on:
  push:
    branches:
      - releases;

name: Deploy Extension
jobs:
  build:
      name: "Build and deploy extension"
      strategy:
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: '16'
            cache: 'npm'
            check-latest: true
        - run: npm install
        - run: npm ci
        - name: Publish to Open VSX Registry
          uses: HaaLeo/publish-vscode-extension@v0
          with:
            pat: ${{ secrets.OPEN_VSX_TOKEN }}
